sudo: required
language: python
services:
  - docker
env:
  global:
    - TRAVIS_COMMIT_SHORT=${TRAVIS_COMMIT::8}

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - pypy
install:
  - pip install tox-travis
script:
  - tox
before_install:
  - pip install codecov
after_success:
  - codecov

notifications:
  email: false
  
deploy:
  - provider: script
    script: make travis-build-docker
    on:
      branch: master
  - provider: pypi
    user: mybook
    distributions: sdist bdist_wheel
    password:
      secure: 3JtgqlD3CptovnS2LW2ZnewtA7f9UXALtW5UvvA28aADbxDmaIdXgs5QuKrYeY6UXbdXX2MUS1VyLZLpt0/yYthwmK1WCxCkcCoYRhjwZkgfkH3UUZTp8K6POu+zaCOnvIqyXTtebzEKlQ2bFrlE+ZM6R0f8ju1mSggK8wxYO//h1eztbkgONJoc38tZYSRJ22AAmskmMpRMzgZp3TxGaE4jFdGcj1CpvnzCijdYYgRmLDwrRa/olT97taKil7ii2IZMzH2yA8/JC9BwJ/YGiHPP+taF/v0f2wLyK1d4WlmtqtQAR6AFKR8gJoPwGhFV2fcv3L0W6FVHdj3V7zFEWmUwdm/VeI0xeD2EGpzXvacJduDLN0RcSbUGIe5CGanFaQJ04NBdmxUNlKqGmUgGS1zYEj+EbpkgLvNFiMjz4GzQx7FSgB/H0Odz3ytmbL2WCiDJgizW6Ovup5WvS3BiBBR+izq0iUC9AGBPqLsjWVQ9O/+REqWlqLA8+uXEeGk1A3jSWzYgfHbrh3Tc4cIiNRPlYFrB0aljbGSNqFEBuQ5v60MwdTuKRDF5bNJNivjPtwOIgtZyLIB5VUWhruSviOvvRxe4Og4uj2WYFZoHCkc5jrpwOYn7Y40L5rn4F9gIVBzg1BgKE9g43dy5p0fXhFTfb2Y0/d3Al851gsnkCI8=
    on:
      tags: true
